"""Add administrator roles and privacy-preserving usage analytics.

Revision ID: 20260728_0009
Revises: 20260725_0008
"""
from alembic import op


revision = "20260728_0009"
down_revision = "20260725_0008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        alter table public.app_users
            add column role text not null default 'user'
            check (role in ('user', 'admin', 'super_admin'));

        update public.app_users
        set role = 'super_admin', updated_at = now()
        where normalized_username = 'admin';

        create table public.analytics_visitors (
            visitor_hash text primary key check (length(visitor_hash) = 64),
            user_id uuid references public.app_users(id) on delete set null,
            first_seen_at timestamptz not null default now(),
            last_seen_at timestamptz not null default now()
        );

        create table public.analytics_events (
            id bigint generated by default as identity primary key,
            visitor_hash text not null check (length(visitor_hash) = 64),
            user_id uuid references public.app_users(id) on delete set null,
            event_type text not null,
            scholar_id uuid references public.scholars(id) on delete set null,
            metadata jsonb not null default '{}'::jsonb,
            created_at timestamptz not null default now()
        );

        create index analytics_visitors_last_seen_idx
            on public.analytics_visitors (last_seen_at desc);
        create index analytics_visitors_user_seen_idx
            on public.analytics_visitors (user_id, last_seen_at desc)
            where user_id is not null;
        create index analytics_events_created_idx
            on public.analytics_events (created_at desc);
        create index analytics_events_type_created_idx
            on public.analytics_events (event_type, created_at desc);
        create index analytics_events_user_created_idx
            on public.analytics_events (user_id, created_at desc)
            where user_id is not null;
        create index analytics_events_scholar_created_idx
            on public.analytics_events (scholar_id, created_at desc)
            where scholar_id is not null;

        revoke all on public.analytics_visitors from public;
        revoke all on public.analytics_events from public;

        do $$
        begin
            if exists (select 1 from pg_roles where rolname = 'scholar_app') then
                grant select, insert, update, delete on public.analytics_visitors to scholar_app;
                grant select, insert, update, delete on public.analytics_events to scholar_app;
                grant usage, select on sequence public.analytics_events_id_seq to scholar_app;
            end if;
        end $$;
    """)


def downgrade() -> None:
    op.execute("""
        drop table if exists public.analytics_events;
        drop table if exists public.analytics_visitors;
        alter table public.app_users drop column if exists role;
    """)
