"""Initial portable PostgreSQL schema.

Revision ID: 20260718_0001
Revises: None
"""
from alembic import op


revision = "20260718_0001"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_SQL = r"""
revoke create on schema public from public;

create table public.scholars (
    id uuid primary key default gen_random_uuid(),
    source text not null,
    source_author_id text not null,
    display_name text not null,
    orcid text,
    works_count integer not null default 0 check (works_count >= 0),
    cited_by_count integer not null default 0 check (cited_by_count >= 0),
    h_index integer not null default 0 check (h_index >= 0),
    quality_flags jsonb not null default '[]'::jsonb,
    raw_json jsonb not null default '{}'::jsonb,
    last_accessed_at timestamptz,
    last_synced_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_author_id)
);

create table public.scholar_aliases (
    id bigint generated by default as identity primary key,
    scholar_id uuid not null references public.scholars(id) on delete cascade,
    alias text not null,
    normalized_alias text not null,
    created_at timestamptz not null default now(),
    unique (scholar_id, normalized_alias)
);

create table public.institutions (
    id uuid primary key default gen_random_uuid(),
    source text not null,
    source_institution_id text not null,
    display_name text not null,
    country_code text,
    raw_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_institution_id)
);

create table public.scholar_institutions (
    scholar_id uuid not null references public.scholars(id) on delete cascade,
    institution_id uuid not null references public.institutions(id) on delete cascade,
    is_last_known boolean not null default false,
    created_at timestamptz not null default now(),
    primary key (scholar_id, institution_id)
);

create table public.works (
    id uuid primary key default gen_random_uuid(),
    source text not null,
    source_work_id text not null,
    doi text,
    title text not null,
    publication_year integer,
    cited_by_count integer not null default 0 check (cited_by_count >= 0),
    raw_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source, source_work_id)
);

create table public.authorships (
    work_id uuid not null references public.works(id) on delete cascade,
    scholar_id uuid not null references public.scholars(id) on delete cascade,
    author_position text,
    position_index integer,
    raw_author_name text not null,
    is_corresponding boolean not null default false,
    created_at timestamptz not null default now(),
    primary key (work_id, scholar_id)
);

create table public.scholar_profiles (
    scholar_id uuid primary key references public.scholars(id) on delete cascade,
    query_name text not null default '',
    payload jsonb not null,
    warnings jsonb not null default '[]'::jsonb,
    errors jsonb not null default '[]'::jsonb,
    quality_flags jsonb not null default '[]'::jsonb,
    workflow_version text not null default '1',
    data_fingerprint text not null,
    generated_at timestamptz not null default now()
);

create table public.profile_status (
    scholar_id uuid primary key references public.scholars(id) on delete cascade,
    version bigint not null default 0 check (version >= 0),
    status text not null default 'ready' check (status in ('ready', 'queued', 'updating', 'failed')),
    updated_at timestamptz not null default now()
);

create table public.refresh_jobs (
    id uuid primary key default gen_random_uuid(),
    scholar_id uuid not null references public.scholars(id) on delete cascade,
    reason text not null,
    status text not null default 'pending' check (status in ('pending', 'running', 'succeeded', 'failed')),
    attempts integer not null default 0 check (attempts >= 0),
    scheduled_at timestamptz not null default now(),
    started_at timestamptz,
    locked_at timestamptz,
    finished_at timestamptz,
    last_error text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table public.app_users (
    id uuid primary key default gen_random_uuid(),
    email text not null,
    normalized_email text not null unique,
    is_active boolean not null default true,
    last_login_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (normalized_email = lower(btrim(normalized_email)))
);

create table public.auth_login_tokens (
    id uuid primary key default gen_random_uuid(),
    email text not null,
    normalized_email text not null,
    token_hash text not null unique check (length(token_hash) = 64),
    expires_at timestamptz not null,
    consumed_at timestamptz,
    request_ip inet,
    created_at timestamptz not null default now()
);

create table public.user_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references public.app_users(id) on delete cascade,
    token_hash text not null unique check (length(token_hash) = 64),
    expires_at timestamptz not null,
    last_seen_at timestamptz not null default now(),
    revoked_at timestamptz,
    user_agent text not null default '',
    request_ip inet,
    created_at timestamptz not null default now()
);

create table public.user_history (
    user_id uuid not null references public.app_users(id) on delete cascade,
    scholar_id uuid not null references public.scholars(id) on delete cascade,
    query_name text not null default '',
    view_count integer not null default 1 check (view_count > 0),
    first_viewed_at timestamptz not null default now(),
    last_viewed_at timestamptz not null default now(),
    primary key (user_id, scholar_id)
);

create table public.favorites (
    user_id uuid not null references public.app_users(id) on delete cascade,
    scholar_id uuid not null references public.scholars(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (user_id, scholar_id)
);

create unique index refresh_jobs_one_active_per_scholar
    on public.refresh_jobs (scholar_id) where status in ('pending', 'running');
create index scholars_last_accessed_idx on public.scholars (last_accessed_at desc);
create index scholar_institutions_institution_idx on public.scholar_institutions (institution_id, scholar_id);
create index works_year_idx on public.works (publication_year desc, id);
create index works_citations_idx on public.works (cited_by_count desc, id);
create index authorships_scholar_idx on public.authorships (scholar_id, work_id);
create index refresh_jobs_claim_idx on public.refresh_jobs (status, scheduled_at) where status = 'pending';
create index refresh_jobs_scholar_idx on public.refresh_jobs (scholar_id);
create index auth_login_tokens_email_recent_idx on public.auth_login_tokens (normalized_email, created_at desc);
create index auth_login_tokens_ip_recent_idx on public.auth_login_tokens (request_ip, created_at desc) where request_ip is not null;
create index auth_login_tokens_expiry_idx on public.auth_login_tokens (expires_at);
create index user_sessions_user_idx on public.user_sessions (user_id);
create index user_sessions_expiry_idx on public.user_sessions (expires_at);
create index user_history_recent_idx on public.user_history (user_id, last_viewed_at desc);
create index user_history_scholar_idx on public.user_history (scholar_id, user_id);
create index favorites_scholar_idx on public.favorites (scholar_id, user_id);

create or replace function public.notify_profile_status_change()
returns trigger
language plpgsql
security invoker
set search_path = pg_catalog, public
as $$
begin
    perform pg_notify(
        'profile_status',
        json_build_object(
            'scholar_id', new.scholar_id,
            'version', new.version,
            'status', new.status,
            'updated_at', new.updated_at
        )::text
    );
    return new;
end;
$$;

create trigger profile_status_notify
after insert or update of version, status, updated_at on public.profile_status
for each row execute function public.notify_profile_status_change();

revoke all on all tables in schema public from public;
revoke all on all sequences in schema public from public;

do $$
begin
    if exists (select 1 from pg_roles where rolname = 'scholar_app') then
        grant usage on schema public to scholar_app;
        grant select, insert, update, delete on all tables in schema public to scholar_app;
        grant usage, select on all sequences in schema public to scholar_app;
        grant execute on function public.notify_profile_status_change() to scholar_app;
    end if;
end $$;
"""


def upgrade() -> None:
    op.execute(SCHEMA_SQL)


def downgrade() -> None:
    op.execute("""
        drop trigger if exists profile_status_notify on public.profile_status;
        drop function if exists public.notify_profile_status_change();
        drop table if exists public.favorites;
        drop table if exists public.user_history;
        drop table if exists public.user_sessions;
        drop table if exists public.auth_login_tokens;
        drop table if exists public.app_users;
        drop table if exists public.refresh_jobs;
        drop table if exists public.profile_status;
        drop table if exists public.scholar_profiles;
        drop table if exists public.authorships;
        drop table if exists public.works;
        drop table if exists public.scholar_institutions;
        drop table if exists public.institutions;
        drop table if exists public.scholar_aliases;
        drop table if exists public.scholars;
    """)
