"""Add audit and rate limiting for public registration.

Revision ID: 20260722_0003
Revises: 20260722_0002
"""
from alembic import op


revision = "20260722_0003"
down_revision = "20260722_0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        create table public.auth_registration_attempts (
            id bigint generated by default as identity primary key,
            request_ip inet,
            success boolean not null default false,
            created_at timestamptz not null default now()
        );

        create index auth_registration_attempts_ip_recent_idx
            on public.auth_registration_attempts (request_ip, created_at desc)
            where request_ip is not null;

        revoke all on public.auth_registration_attempts from public;

        do $$
        begin
            if exists (select 1 from pg_roles where rolname = 'scholar_app') then
                grant select, insert, update, delete on public.auth_registration_attempts to scholar_app;
                grant usage, select on sequence public.auth_registration_attempts_id_seq to scholar_app;
            end if;
        end $$;
    """)


def downgrade() -> None:
    op.execute("drop table if exists public.auth_registration_attempts")
