"""Add persistent API rate limit events.

Revision ID: 20260722_0004
Revises: 20260722_0003
"""
from alembic import op


revision = "20260722_0004"
down_revision = "20260722_0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        create table public.api_rate_limit_events (
            id bigint generated by default as identity primary key,
            user_id uuid not null references public.app_users(id) on delete cascade,
            request_ip inet,
            action text not null check (action in ('search', 'profile')),
            created_at timestamptz not null default now()
        );

        create index api_rate_limit_events_user_recent_idx
            on public.api_rate_limit_events (action, user_id, created_at desc);
        create index api_rate_limit_events_ip_recent_idx
            on public.api_rate_limit_events (action, request_ip, created_at desc)
            where request_ip is not null;

        revoke all on public.api_rate_limit_events from public;

        do $$
        begin
            if exists (select 1 from pg_roles where rolname = 'scholar_app') then
                grant select, insert, delete on public.api_rate_limit_events to scholar_app;
                grant usage, select on sequence public.api_rate_limit_events_id_seq to scholar_app;
            end if;
        end $$;
    """)


def downgrade() -> None:
    op.execute("drop table if exists public.api_rate_limit_events")
