"""Replace email magic links with local username/password authentication.

Revision ID: 20260722_0002
Revises: 20260718_0001
"""
from alembic import op


revision = "20260722_0002"
down_revision = "20260718_0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        alter table public.app_users
            alter column email drop not null,
            alter column normalized_email drop not null,
            add column username text,
            add column normalized_username text,
            add column password_hash text;

        update public.app_users
        set username = 'legacy-' || id::text,
            normalized_username = 'legacy-' || id::text,
            password_hash = 'disabled';

        alter table public.app_users
            alter column username set not null,
            alter column normalized_username set not null,
            alter column password_hash set not null,
            add constraint app_users_normalized_username_key unique (normalized_username),
            add constraint app_users_normalized_username_check
                check (normalized_username = lower(btrim(normalized_username))),
            drop column normalized_email,
            drop column email;

        create table public.auth_login_attempts (
            id bigint generated by default as identity primary key,
            normalized_username text not null,
            request_ip inet,
            success boolean not null default false,
            created_at timestamptz not null default now()
        );

        create index auth_login_attempts_username_recent_idx
            on public.auth_login_attempts (normalized_username, created_at desc);
        create index auth_login_attempts_ip_recent_idx
            on public.auth_login_attempts (request_ip, created_at desc)
            where request_ip is not null;

        drop table public.auth_login_tokens;

        revoke all on public.auth_login_attempts from public;

        do $$
        begin
            if exists (select 1 from pg_roles where rolname = 'scholar_app') then
                grant select, insert, update, delete on public.auth_login_attempts to scholar_app;
                grant usage, select on sequence public.auth_login_attempts_id_seq to scholar_app;
            end if;
        end $$;
    """)


def downgrade() -> None:
    op.execute("""
        drop table if exists public.auth_login_attempts;

        create table public.auth_login_tokens (
            id uuid primary key default gen_random_uuid(),
            email text not null,
            normalized_email text not null,
            token_hash text not null unique check (length(token_hash) = 64),
            expires_at timestamptz not null,
            consumed_at timestamptz,
            request_ip inet,
            created_at timestamptz not null default now()
        );
        create index auth_login_tokens_email_recent_idx
            on public.auth_login_tokens (normalized_email, created_at desc);
        create index auth_login_tokens_ip_recent_idx
            on public.auth_login_tokens (request_ip, created_at desc)
            where request_ip is not null;
        create index auth_login_tokens_expiry_idx
            on public.auth_login_tokens (expires_at);

        alter table public.app_users
            add column email text,
            add column normalized_email text;

        update public.app_users
        set email = username || '@local.invalid',
            normalized_email = normalized_username || '@local.invalid';

        alter table public.app_users
            drop constraint if exists app_users_normalized_username_check,
            drop constraint if exists app_users_normalized_username_key,
            drop column password_hash,
            drop column normalized_username,
            drop column username,
            alter column normalized_email set not null,
            alter column email set not null,
            add constraint app_users_normalized_email_key unique (normalized_email),
            add constraint app_users_normalized_email_check
                check (normalized_email = lower(btrim(normalized_email)));

        do $$
        begin
            if exists (select 1 from pg_roles where rolname = 'scholar_app') then
                grant select, insert, update, delete on public.auth_login_tokens to scholar_app;
            end if;
        end $$;
    """)
